// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJk-PNp4U6nbFdL7N8IYPTKlW3lc3C1y0',
    appId: '1:359845236304:web:2cb7bc53b08f3e634e8b55',
    messagingSenderId: '359845236304',
    projectId: 'aura-jewelry-app',
    authDomain: 'aura-jewelry-app.firebaseapp.com',
    storageBucket: 'aura-jewelry-app.firebasestorage.app',
    measurementId: 'G-BFHH2M5S5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHaiVIF1gMHUtslvjMSIxUJYWZTdjsMlc',
    appId: '1:359845236304:android:b63c1a122e0559af4e8b55',
    messagingSenderId: '359845236304',
    projectId: 'aura-jewelry-app',
    storageBucket: 'aura-jewelry-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMM_dF-_hDhQfP3uylgzgNSVXHc8N-uRI',
    appId: '1:359845236304:ios:2bc5039da32275e24e8b55',
    messagingSenderId: '359845236304',
    projectId: 'aura-jewelry-app',
    storageBucket: 'aura-jewelry-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMM_dF-_hDhQfP3uylgzgNSVXHc8N-uRI',
    appId: '1:359845236304:ios:2bc5039da32275e24e8b55',
    messagingSenderId: '359845236304',
    projectId: 'aura-jewelry-app',
    storageBucket: 'aura-jewelry-app.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJk-PNp4U6nbFdL7N8IYPTKlW3lc3C1y0',
    appId: '1:359845236304:web:ffad95bad03438934e8b55',
    messagingSenderId: '359845236304',
    projectId: 'aura-jewelry-app',
    authDomain: 'aura-jewelry-app.firebaseapp.com',
    storageBucket: 'aura-jewelry-app.firebasestorage.app',
    measurementId: 'G-LV2Y7H7S3D',
  );
}
